version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "8089:8088"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: hw_11
      POSTGRES_USER: msmiracle18
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
